# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('AND', 'AS', 'ASCD', 'BY', 'COLLECT', 'COLON', 'COMMA', 'DASH', 'DESC', 'DOT', 'ELSE', 'EQ', 'EQEQ', 'EVERY', 'FLATTEN', 'FOR', 'FUNCTION', 'GE', 'IF', 'IN', 'INTERSECTION', 'IS', 'LANGLE', 'LCURLY', 'LE', 'LET', 'LPAREN', 'LSQUARE', 'NAME', 'NOT', 'NQ', 'NUMBER', 'OR', 'ORDER', 'PLUS', 'PROPER', 'RANGLE', 'RCURLY', 'RETURN', 'RPAREN', 'RSQUARE', 'SATISFIES', 'SLASH', 'SOME', 'STAR', 'STRING', 'SUBSET', 'SUPERSET', 'THEN', 'UNION', 'WHERE', 'WITH'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_STRING_LITERAL1>\\"[^"]*\\")|(?P<t_STRING_LITERAL2>\\\'[^\']*\\\')|(?P<t_NAME>([a-zA-Z_])(([a-zA-Z_])|([0-9]))*)|(?P<t_CONST_HEX>0[xX]([a-fA-F0-9])+)|(?P<t_CONST_FLOAT1>([0-9])+([Ee][+-]?([0-9])+))|(?P<t_CONST_FLOAT2>([0-9])*\\.([0-9])+([Ee][+-]?([0-9])+)?)|(?P<t_CONST_DEC_OCT>([0-9])+)|(?P<t_COMMENT>(/\\*([^*]|[\\r\\n]|(\\*+([^*/]|[\\r\\n])))*\\*+/)|(//.*))|(?P<t_newline>\\n+)|(?P<t_GE>\\>=)|(?P<t_LE>\\<=)|(?P<t_COLON>\\:)|(?P<t_DASH>\\-)|(?P<t_DOT>\\.)|(?P<t_EQEQ>==)|(?P<t_LANGLE>\\<)|(?P<t_LCURLY>\\{)|(?P<t_LPAREN>\\()|(?P<t_LSQUARE>\\[)|(?P<t_NQ>!=)|(?P<t_PLUS>\\+)|(?P<t_RANGLE>\\>)|(?P<t_RCURLY>\\})|(?P<t_RPAREN>\\))|(?P<t_RSQUARE>\\])|(?P<t_STAR>\\*)|(?P<t_UNION>\\|)|(?P<t_COMMA>,)|(?P<t_EQ>=)|(?P<t_INTERSECTION>&)|(?P<t_SLASH>/)', [None, ('t_STRING_LITERAL1', 'STRING_LITERAL1'), ('t_STRING_LITERAL2', 'STRING_LITERAL2'), ('t_NAME', 'NAME'), None, None, None, None, ('t_CONST_HEX', 'CONST_HEX'), None, ('t_CONST_FLOAT1', 'CONST_FLOAT1'), None, None, None, ('t_CONST_FLOAT2', 'CONST_FLOAT2'), None, None, None, None, ('t_CONST_DEC_OCT', 'CONST_DEC_OCT'), None, ('t_COMMENT', 'COMMENT'), None, None, None, None, None, ('t_newline', 'newline'), (None, 'GE'), (None, 'LE'), (None, 'COLON'), (None, 'DASH'), (None, 'DOT'), (None, 'EQEQ'), (None, 'LANGLE'), (None, 'LCURLY'), (None, 'LPAREN'), (None, 'LSQUARE'), (None, 'NQ'), (None, 'PLUS'), (None, 'RANGLE'), (None, 'RCURLY'), (None, 'RPAREN'), (None, 'RSQUARE'), (None, 'STAR'), (None, 'UNION'), (None, 'COMMA'), (None, 'EQ'), (None, 'INTERSECTION'), (None, 'SLASH')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
